Zummit-Africa-Inc/zapi-lambda-core

- .env.example
- .eslintrc.js
- package.json
- src/app.module.ts
- src/main.ts
- Implemented RabbitMq
- Removed some duplicate installations
> Implemented Comms with notification service via RabbitMq

- src/app.module.ts
- src/database/migration/1661499876749-profileEntityCreated.ts
- src/database/migration/1661507038489-fixProfile.ts
- src/entities/profile.entity.ts
- src/profile/dto/create-profile.dto.ts
- src/profile/profile.controller.spec.ts
- src/profile/profile.controller.ts
- src/profile/profile.module.ts
- src/profile/profile.service.spec.ts
- src/profile/profile.service.ts
> profile logic

- package-lock.json
- package.json
- src/app.module.ts
- src/common/enums/httpMethods.enum.ts
- src/database/migration/1661895602787-endpointEntity.ts
- src/endpoints/endpoints.controller.spec.ts
- src/endpoints/endpoints.controller.ts
- src/endpoints/endpoints.module.ts
- src/endpoints/endpoints.service.spec.ts
- src/endpoints/endpoints.service.ts
- src/endpoints/interface/endpoint.interface.ts
- src/entities/endpoint.entity.ts
- src/subscription/subscription.controller.spec.ts
- src/subscription/subscription.controller.ts
- src/subscription/subscription.module.ts
- src/subscription/subscription.service.spec.ts
- src/subscription/subscription.service.ts
This includes the Entity schema, module structure( controller, service, etc files), relationship with other entity schemas
> create endpoint architecture

- .env.example
- src/listener.ts
- Updated env.example
- Updated listener.ts
> Little fixes regarding microservices

- src/api/api.module.ts
- src/endpoints/endpoints.controller.ts
> fixed api.module issue

- package-lock.json
- package.json
- src/api/api.controller.ts
- src/api/api.module.ts
- src/api/api.service.ts
- src/api/dto/create-api.dto.ts
Endpoint to add an API and Endpoint to delete an API
> Adding and Deleting an Api

- .env.example
- src/common/constants/config.constant.ts
- src/common/interfaces/subscriptionToken.interface.ts
- src/database/migration/1663170625869-subscriptionToken.ts
- src/entities/subscription.entity.ts
- src/subscription/dto/create-subscription.dto.ts
- src/subscription/subscription.controller.ts
- src/subscription/subscription.module.ts
- src/subscription/subscription.service.ts
1. a subscription column was added to the subscription enitity
2. a migration file was generated for this entity change
3. a user can subscribe to an api and a token will be generated and stored in the process for this particular subscription
> first implementation for API subscription

- src/api/api.controller.ts
- src/api/api.service.ts
- src/api/dto/create-api.dto.ts
added Endpoint to get an Api
**Apart from code formatting made the number of changes high
> Endpoint to get an Api

- src/api/api.controller.ts
- src/api/api.module.ts
- src/api/api.service.ts
- src/api/dto/update-api.dto.ts
- src/database/migration/1663253819370-apiUpdate.ts
- src/entities/api.entity.ts
- added **logo_url, api_website and term_of_use**  columns  to entity file
- 
- create DTO file showing all the optional columns that can be updated on the API Table
- Generated migration file for the updated entity
> edit an API

- src/profile/dto/update-profile.dto.ts
- src/profile/profile.controller.ts
- src/profile/profile.service.ts
* added Endpoint to edit a user profile
* added a updateProfile.dto.ts file
> Endpoint to edit a user profile

- package.json
- src/api/api.controller.ts
- src/api/api.service.ts
- Endpoint to get all APIs with search, sort and pagination.
> Endpoint to get all APIs

- src/analytics/analytics.controller.ts
- src/analytics/analytics.service.ts
- src/api/api.controller.ts
- src/common/helpers/response/Response.ts
- Added endpoints to get analytics and logs
- Added a custom response type for paginated response
> Added endpoints to get analytics and logs

- src/categories/categories.controller.ts
- src/categories/categories.module.ts
- src/categories/categories.service.ts
- src/entities/category.entity.ts
fix for issue https://github.com/Zummit-Africa-Inc/zapi-lambda-core/issues/47
> refactored service to get all apis in a category

- src/database/migration/1664832949011-cascadeEntity.ts
- src/entities/api.entity.ts
- src/entities/profile.entity.ts
- src/entities/subscription.entity.ts
when a profile is deleted all its relationships are deleted (API and Subscriptions)
> Profile delete

- .env.example
- src/subscription/subscription.service.ts
- Setup subscription service to make call notification service to notify user about new subscriptions 
- updated env.example file
> Subscription notification feature

- src/categories/categories.controller.ts
- src/categories/categories.service.ts
- Endpoint deletes a category and moves all apis under that category to a general category
> created endpoint to delete a category

- src/common/interfaces/loggerJson.interface.ts
- src/database/migration/1665699605623-updateEndpoint.ts
- src/endpoints/endpoints.service.ts
- src/entities/logger.entity.ts
fix issue relating to updating and deleting of endpoint
> Endpoint update

- src/subscription/subscription.controller.ts
- src/subscription/subscription.service.ts
- Prevent user from subscribing to their own api
> prevent user from subscribing to their own api

- src/api/api.service.ts
- src/endpoints/endpoints.service.ts
fix duplicate api error message
and clean Id condition checks
> Clean up and error fix

- src/analytics/analytics.controller.ts
- src/api/api.controller.ts
- src/api/api.service.ts
- src/categories/categories.controller.ts
- src/common/guards/access-token.guard.ts
- src/common/guards/authorization.guard.ts
- src/endpoints/endpoints.controller.ts
- src/profile/profile.controller.ts
- src/subscription/subscription.controller.ts
- Added authorization guard on update and delete endpoints
- Moved Authentication guard to controller level
- Added profileId query fields to endpoints that require authorisation
- Removed manual isOwner checking method
> Created Authorization guard

- src/categories/categories.controller.ts
- src/categories/categories.service.ts
- src/common/enums/invalidCategories.enum.ts
- Added enum to hold list of invalid categories
- Added endpoint to return only valid categories when user is trying to add an api
- remove delete category controller
> Hide categories

- src/api/api.controller.ts
- src/api/api.service.ts
Returns the top 20 most subscribed apis (Popular APIs) in the system
> Popular apis

- src/analytics/analytics.controller.ts
- src/api/api.controller.ts
- src/categories/categories.controller.ts
- src/common/guards/authentication.guard.ts
- src/endpoints/endpoints.controller.ts
- src/profile/profile.controller.ts
- src/subscription/subscription.controller.ts
- src/subscription/subscription.service.ts
- Renamed access token guard to authentication guard
- Refactored subscription db queries for better speed
> Subscription and Authentication refactor

- src/subscription/subscription.controller.ts
- src/subscription/subscription.service.ts
Create endpoint to remove all subscriptions from an api
> Complete unsubscription

- src/common/enums/endpointHeaderType.enum.ts
- src/common/interfaces/endpoint.interface.ts
- src/common/interfaces/loggerJson.interface.ts
- src/database/migration/1666817301630-endpointRefactor.ts
- src/database/migration/1666864950347-endpointRefactor.ts
- src/endpoints/dto/create-endpoint.dto.ts
- src/endpoints/dto/update-endpoint.dto.ts
- src/endpoints/endpoints.service.ts
- src/endpoints/interface/endpoint.interface.ts
- src/entities/endpoint.entity.ts
- Added body to endpoint entity
- Did some refactors
- New migration file
> Added body to endpoint entity, and a few other refactors

- src/subscription/subscription.controller.ts
-Renamed token name to x-zapi-request-token
> fixed auth name

- src/categories/categories.controller.ts
- src/categories/categories.service.ts
- src/common/enums/invalidCategories.enum.ts
- Updated invalid category enum
- get all apis in a category endpoint only returns public apis
> Invalid cat enum

- src/database/migration/1667901709300-apiContributorColumn.ts
- src/entities/api.entity.ts
api contributor column created.. migration file generated ......
> additional column added to the api entity

- src/categories/categories.controller.ts
- src/discussion/discussion.service.ts
- valid category does not require authentication
- fixed bug in getdiscussionAndComments endpoint
> Discussion fix

- src/api/api.controller.ts
- src/api/api.module.ts
- src/api/api.service.ts
- src/api/dto/add-api-rating.dto.ts
- src/database/migration/1668328176156-review.ts
- src/database/migration/1668371138644-updatedApiRating.ts
- src/entities/api.entity.ts
- src/entities/review.entity.ts
- created endpoint to add rating to an api
- created entity and migration file for a review table where rating and review of an api can be added
- updated api entity file and generated migration file so rating can be stored as a decimal
> Api reviews

- src/api/api.controller.ts
- src/api/api.service.ts
- endpoint to return all reviews of an api
> Reviews and ratings

- src/api/dto/add-api-rating.dto.ts
- src/database/migration/1668795118396-reviewRefactor.ts
- src/entities/review.entity.ts
- added reviewer field to review entity file and created migration file
- updated add api review dto
> Api reviews fix

- src/api/dto/add-api-rating.dto.ts
- src/database/migration/1669615535652-reviewUpdate.ts
- src/entities/review.entity.ts
- fixed migration issue
- updated add-rating dto file
- updated entity file
> Api review migration fix

- src/common/enums/invalidCategories.enum.ts
- src/subscription/subscription.controller.ts
- src/subscription/subscription.service.ts
Paginated get test endpoint, one can now filter with apiId
> Paginated getDevTests endpoint

- src/common/constants/config.constant.ts
- src/common/model/sharedEntity.ts
- src/database/migration/1671550374695-updateDateDecorator.ts
- src/endpoints/endpoints.service.ts
- src/entities/invitation.entity.ts
- src/invitation/invitation.module.ts
- src/invitation/invitation.service.ts
1. updatedOn column modified with a new decorator,
2. updates on endpoints to reflect on API entity also
> updatedOn Column modified in the shared entity

- src/discussion/discussion.controller.ts
- src/discussion/discussion.module.ts
- src/discussion/discussion.service.ts
- src/review/review.service.ts
Fixed a small issue in discussion resource, 
Added reviewer name to reviews
> Update get discussion and create profile endpoint

- src/api/api.service.ts
- src/api/dto/create-api-and-endpoints.dto.ts
- src/api/dto/create-api.dto.ts
- src/api/dto/update-api.dto.ts
- Restructure the payload for creating an API with its endpoints
- Restore **base_url** after previously renaming it to **baseUrl**
> Create api with endpoints

- src/api/api.service.ts
- src/api/dto/create-api-and-endpoints.dto.ts
- src/endpoints/dto/create-endpoint.dto.ts
- src/endpoints/endpoints.controller.ts
- Make endpoints field optional
- Rename createEndpointDto to endpoints
- Document creating multiple endpoints
- Remove logo_url when creating api
> Endpoint Updates

- src/api/api.service.ts
- src/api/dto/create-api-and-endpoints.dto.ts
- src/common/interfaces/endpoint-impl.interface.ts
- src/common/interfaces/endpoint.interface.ts
- src/endpoints/dto/create-endpoint.dto.ts
- Check for duplicates when saving a new API with endpoints and only save the first on, returning the duplicates in an array
- Documenting **CreateEndpointDto**
> Api endpoints

- src/common/interfaces/endpoint-impl.interface.ts
- src/common/interfaces/endpoint.interface.ts
- src/endpoints/endpoints.controller.ts
- src/endpoints/endpoints.service.ts
> changed value type from object to string in endpointdto

- src/api/api.service.ts
- src/endpoints/dto/create-endpoint.dto.ts
updated header, body and query in createEndpointdto to be optional and also made fixed a bug when updating an API
> updated header, body and query in createEndpointdto to be optional and also made fixed a bug when updating an API
